apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: container2
          image: rohinidocker550/httpd
          ports:
            - containerPort: 80
              protocol: TCP
